services:
  back:
    build: ./back/app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
    depends_on:
      - db

  front:
    build: ./front/app
    ports:
       - "3000:80"
    environment:
      - NUXT_API_BASE=http://back:8000
    depends_on:
      - back

  db:
    image: postgres:17-bookworm
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=localdb
    volumes:
      - pgdata-ecs:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata-ecs: